title: Artist Lockers

preferences:
  dark: null

# Jekyll options
theme: null
permalink: pretty
plugins:
  - jekyll-link-attributes
kramdown:
  input: GFM
  template: ""
defaults:
  - scope: {path: ""}
    values:
      preferences: locker
exclude:
  - CNAME
  - README.md
  - Gemfile
  - vendor
  - bin
  - ".*"
  - "*.py"
  - "*.toml"
  - "*.yaml"
  - "*.lock"

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
