version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "[%(levelname)-8s] %(name)-15s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stderr

root:
  level: INFO
  handlers: [console]

loggers:
  discord.client:
    level: ERROR
    propagate: true
  discord.gateway:
    level: ERROR
    propagate: true
